### ISSUE TITLE
Has the users own profile also be on the browse page?

### ISSUE THREAD

**Issue by triinuaug** [Bakhtiyar-Garashov/wad20-homework3#11]

**Comment by Bakhtiyar-Garashov** [comment]
I dont know exactly but in the api, first user is John Doe. Maybe we can simply delete that user after fetching data from api. I am not sure.

**Comment by Bakhtiyar-Garashov** [comment]
I just checked that in our previous homework (the one with Jquery), it also had 5 users in browse page including the one that current profile.
